Repository vechain/vechain-sdk-js, pull requests merged in 2024-08, with the labels that each got.

#1125 1103-interface-vechaindatamodel
  docs/diagrams/architecture/vcdm.md
  packages/core/src/vcdm/VeChainDataModel.ts
  packages/core/src/vcdm/index.ts
Labels: Type: Enhancement, Type: Feature, Size: Small, Priority: High

#1127 1117 class txt
  docs/diagrams/architecture/vcdm.md
  packages/core/src/certificate/certificate.ts
  packages/core/src/core.ts
  packages/core/src/hash/blake2b256.ts
  packages/core/src/keystore/keystore.ts
  packages/core/src/utils/data/data.ts
  packages/core/src/utils/index.ts
  packages/core/src/utils/txt/index.ts
  packages/core/src/utils/txt/txt.ts
  packages/core/src/vcdm/Txt.ts
  packages/core/src/vcdm/index.ts
  packages/core/tests/bloom/bloom.unit.test.ts
  packages/core/tests/hash/blake2b256.unit.test.ts
  packages/core/tests/hash/hash.unit.test.ts
  packages/core/tests/secp256k1/fixture.ts
  packages/core/tests/utils/txt/txt.unit.test.ts
  packages/core/tests/vcdm/Txt.unit.test.ts
  packages/errors/src/available-errors/index.ts
  packages/errors/src/available-errors/vcdm/InvalidCastType.ts
  packages/errors/src/available-errors/vcdm/index.ts
  packages/network/src/signer/signers/vechain-private-key-signer/vechain-private-key-signer.ts
  packages/network/tests/signer/signers/vechain-private-key-signer/vechain-private-key-signer.unit.test.ts
Labels: Type: Enhancement, Type: Feature, Size: Small, Priority: High

#1147 1110-class-HexInt
  .eslintrc.json
  docs/diagrams/architecture/vcdm.md
  packages/core/src/hash/blake2b256.ts
  packages/core/src/utils/hex/_Hex.ts
  packages/core/src/vcdm/Hex.ts
  packages/core/src/vcdm/HexInt.ts
  packages/core/src/vcdm/Quantity.ts
  packages/core/src/vcdm/ThorId.ts
  packages/core/src/vcdm/index.ts
  packages/core/tests/bloom/bloom.unit.test.ts
  packages/core/tests/hash/blake2b256.unit.test.ts
  packages/core/tests/keystore/keystore.unit.test.ts
  packages/core/tests/mnemonic/fixture.ts
  packages/core/tests/mnemonic/mnemonic.unit.test.ts
  packages/core/tests/rlp/helpers.unit.test.ts
  packages/core/tests/rlp/rlp.fixture.ts
  packages/core/tests/rlp/rlp.unit.test.ts
  packages/core/tests/transaction/fixture.ts
  packages/core/tests/transaction/transaction-handler.unit.test.ts
  packages/core/tests/transaction/transaction.unit.test.ts
  packages/core/tests/vcdm/Hex.unit.test.ts
  packages/core/tests/vcdm/HexInt.unit.test.ts
  packages/network/src/provider/providers/vechain-provider/vechain-provider.ts
  packages/network/src/provider/utils/formatter/blocks/formatter.ts
  packages/network/src/provider/utils/formatter/logs/formatter.ts
  packages/network/src/provider/utils/formatter/transactions/formatter.ts
  packages/network/src/provider/utils/rpc-mapper/methods-map/methods/eth_subscribe/eth_subscribe.ts
  packages/network/src/provider/utils/rpc-mapper/methods-map/methods/eth_syncing/eth_syncing.ts
  packages/network/src/signer/signers/vechain-private-key-signer/vechain-private-key-signer.ts
  packages/network/tests/provider/providers/fixture.ts
  packages/network/tests/provider/rpc-mapper/methods/eth_blockNumber/eth_blockNumber.testnet.test.ts
  packages/network/tests/provider/rpc-mapper/methods/eth_getBalance/fixture.ts
  packages/network/tests/provider/rpc-mapper/methods/eth_getBlockByNumber/fixture.ts
  packages/network/tests/provider/rpc-mapper/methods/eth_getBlockReceipts/fixture.ts
Labels: Type: Documentation, Type: Enhancement, Type: Feature, Type: Testing, Type: Design, Size: Small, Priority: High

#1149 1110 class HexUInt
  docs/diagrams/architecture/vcdm.md
  packages/core/src/utils/hex/_Hex.ts
  packages/core/src/utils/hex/index.ts
  packages/core/src/utils/hex/types.d.ts
  packages/core/src/utils/index.ts
  packages/core/src/vcdm/Hex.ts
  packages/core/src/vcdm/HexUInt.ts
  packages/core/src/vcdm/index.ts
  packages/core/tests/utils/hex/hex.unit.test.ts
  packages/core/tests/vcdm/Hex.unit.test.ts
  packages/core/tests/vcdm/HexUInt.unit.test.ts
Labels: Type: Enhancement, Type: Feature, Size: Small, Priority: High

#1172 feat: 1105 class Address.ts documented in examples and diagrams
  docs/accounts.md
  docs/address.md
  docs/diagrams/architecture/vcdm.md
  docs/examples/accounts/pubkey.ts
  docs/examples/address/address-derivation.ts
  docs/examples/address/address-validation.ts
  packages/core/src/vcdm/Address.ts
Labels: Type: Documentation, Size: Small, Priority: High

#1175 1114 class revision
  docs/diagrams/architecture/vcdm.md
  packages/core/src/utils/index.ts
  packages/core/src/utils/revision/index.ts
  packages/core/src/utils/revision/revision.ts
  packages/core/src/vcdm/Hex.ts
  packages/core/src/vcdm/HexUInt.ts
  packages/core/src/vcdm/Quantity.ts
  packages/core/src/vcdm/Revision.ts
  packages/core/src/vcdm/ThorId.ts
  packages/core/src/vcdm/index.ts
  packages/core/tests/utils/revision/revision.unit.test.ts
  packages/core/tests/vcdm/Quantity.unit.test.ts
  packages/core/tests/vcdm/Revision.unit.test.ts
  packages/network/src/thor-client/accounts/accounts-module.ts
  packages/network/src/thor-client/blocks/blocks-module.ts
  packages/network/src/thor-client/transactions/transactions-module.ts
Labels: Type: Documentation, Type: Feature, Type: Testing, Size: Small, Priority: High

#1176 feat: class `Mnemonic`
  docs/accounts.md
  docs/diagrams/architecture/vcdm.md
  docs/examples/accounts/bip32.ts
  docs/examples/accounts/bip39.ts
  docs/examples/accounts/keystore.ts
  docs/examples/transactions/fee-delegation.ts
  docs/transactions.md
  packages/core/src/core.ts
  packages/core/src/mnemonic/index.ts
  packages/core/src/mnemonic/mnemonic.ts
  packages/core/src/mnemonic/types.d.ts
  packages/core/src/utils/const/index.ts
  packages/core/src/utils/const/mnemonic.ts
  packages/core/src/vcdm/Address.ts
  packages/core/src/vcdm/Mnemonic.ts
  packages/core/src/vcdm/index.ts
  packages/core/tests/hdnode/hdnode.unit.test.ts
  packages/core/tests/mnemonic/mnemonic.unit.test.ts
Labels: Type: Feature, Size: Small

#1178 feat: class `Account`
  docs/diagrams/architecture/vcdm.md
  packages/core/src/hash/Blake2b256.ts
  packages/core/src/hash/Keccak256.ts
  packages/core/src/hash/Sha256.ts
  packages/core/src/vcdm/Address.ts
  packages/core/src/vcdm/Mnemonic.ts
  packages/core/src/vcdm/Revision.ts
  packages/core/src/vcdm/VeChainDataModel.ts
  packages/core/src/vcdm/account/Account.ts
  packages/core/src/vcdm/account/ExternallyOwnedAccount.ts
  packages/core/src/vcdm/account/index.ts
  packages/core/src/vcdm/index.ts
  packages/core/tests/vcdm/account/ExternallyOwnedAccount.unit.test.ts
Labels: Type: Feature, Size: Medium

#1198 feat: 1107 class bloomfilter
  docs/bloom-filter.md
  docs/diagrams/architecture/vcdm.md
  docs/examples/bloom/bloom.ts
  packages/core/src/bloom/bloom.ts
  packages/core/src/bloom/index.ts
  packages/core/src/core.ts
  packages/core/src/encoding/rlp/helpers/numerickind.ts
  packages/core/src/encoding/rlp/kind/hexblobkinds/hexblob.ts
  packages/core/src/hash/Blake2b256.ts
  packages/core/src/hash/Keccak256.ts
  packages/core/src/hash/Sha256.ts
  packages/core/src/keystore/cryptography/experimental/keystore.ts
  packages/core/src/keystore/types.d.ts
  packages/core/src/utils/bloom/bloom.ts
  packages/core/src/utils/bloom/index.ts
  packages/core/src/utils/index.ts
  packages/core/src/utils/units/units.ts
  packages/core/src/vcdm/Address.ts
  packages/core/src/vcdm/BloomFilter.ts
  packages/core/src/vcdm/Hex.ts
  packages/core/src/vcdm/HexInt.ts
  packages/core/src/vcdm/Mnemonic.ts
  packages/core/src/vcdm/Quantity.ts
  packages/core/src/vcdm/Revision.ts
  packages/core/src/vcdm/account/Account.ts
  packages/core/src/vcdm/account/ExternallyOwnedAccount.ts
  packages/core/src/vcdm/index.ts
  packages/core/tests/bloom/bloom.unit.test.ts
  packages/core/tests/bloom/fixture.ts
  packages/core/tests/utils/bloom/bloom.unit.test.ts
  packages/core/tests/utils/bloom/fixture.ts
  packages/core/tests/vcdm/BloomFilter.unit.test.ts
  packages/network/src/thor-client/blocks/blocks-module.ts
  packages/network/tests/thor-client/blocks/blocks.testnet.test.ts
Labels: Type: Documentation, Type: Enhancement, Type: Feature, Type: Testing, Size: Medium, Priority: High

#1213 refactor: `InvalidHTTPRequest`
  .github/workflows/test-apps.yml
  .github/workflows/unit-integration-test-browser.yml
  .github/workflows/unit-integration-test.yml
  apps/sdk-hardhat-integration/test/VechainHelloWorldWithNonEmptyConstructor.testnet.test.ts
  package.json
  packages/core/tests/vcdm/Address.unit.test.ts
  packages/errors/src/available-errors/http/http.ts
  packages/errors/src/helpers/helpers.ts
  packages/errors/tests/available-errors/http.unit.test.ts
  packages/hardhat-plugin/src/index.ts
  packages/hardhat-plugin/src/type-extensions.ts
  packages/network/src/provider/providers/hardhat-provider/hardhat-provider.ts
  packages/network/src/provider/utils/rpc-mapper/methods-map/methods/eth_sendRawTransaction/eth_sendRawTransaction.ts
  packages/network/src/provider/utils/rpc-mapper/methods-map/methods/eth_sendTransaction/eth_sendTransaction.ts
  packages/network/src/utils/http/http-client.ts
  packages/network/tests/utils/http/http-client.solo.test.ts
  yarn.lock
Labels: Type: Enhancement, Size: Medium

#1214 chore: bundling only package code
  packages/core/package.json
  packages/errors/package.json
  packages/ethers-adapter/package.json
  packages/logging/package.json
  packages/network/package.json
  packages/rpc-proxy/package.json
Labels: Type: Enhancement, Size: Small
