Repository vechain/vechain-sdk-js, pull requests merged in 2024-09, with the labels that each got.

#1227 1113 fixed point number
  docs/diagrams/architecture/vcdm.md
  packages/core/src/vcdm/FPN.ts
  packages/core/src/vcdm/Hex.ts
  packages/core/src/vcdm/ThorId.ts
  packages/core/src/vcdm/index.ts
  packages/core/tests/vcdm/FPN.unit.test.ts
  packages/core/tests/vcdm/ThorId.unit.test.ts
Labels: Type: Documentation, Type: Enhancement, Type: Feature, Size: Large, Priority: High, dependencies

#1235 feat: 1109 HDCNode class in dev...
  docs/accounts.md
  docs/diagrams/architecture/core-package.md
  docs/diagrams/architecture/hdkey.md
  docs/diagrams/architecture/vcdm.md
  docs/examples/accounts/bip32.ts
  docs/examples/accounts/pubkey.ts
  docs/examples/transactions/fee-delegation.ts
  docs/templates/accounts.md
  docs/transactions.md
  packages/core/src/core.ts
  packages/core/src/hash/Blake2b256.ts
  packages/core/src/hash/Keccak256.ts
  packages/core/src/hash/Sha256.ts
  packages/core/src/hdkey/HDKey.ts
  packages/core/src/hdkey/index.ts
  packages/core/src/hdnode/hdnode.ts
  packages/core/src/utils/const/hdnode.ts
  packages/core/src/utils/const/index.ts
  packages/core/src/utils/hdnode/hdnode.ts
  packages/core/src/utils/hdnode/index.ts
  packages/core/src/utils/index.ts
  packages/core/src/vcdm/Address.ts
  packages/core/src/vcdm/FPN.ts
  packages/core/src/vcdm/Mnemonic.ts
  packages/core/tests/hdkey/hdkey.unit.test.ts
  packages/core/tests/hdnode/fixture.ts
  packages/core/tests/utils/hdnode/fixture.ts
  packages/core/tests/utils/hdnode/hdnode.unit.test.ts
  packages/core/tests/vcdm/FPN.unit.test.ts
  packages/core/tests/vcdm/mnemonic/Mnemonic.unit.test.ts
  packages/errors/src/available-errors/hdkey/hdnode.ts
  packages/errors/src/available-errors/hdkey/index.ts
  packages/errors/src/available-errors/hdnode/index.ts
  packages/errors/src/available-errors/index.ts
  packages/errors/tests/available-errors/hdkey.unit.test.ts
  packages/hardhat-plugin/tests/hardhat-mock-projects/simple-vechain-hardhat-project/hardhat.config.ts
  packages/hardhat-plugin/tests/helpers/fixture.ts
  packages/network/src/provider/helpers/provider-internal-wallets/hd-wallet/provider-internal-hd-wallet.ts
  packages/network/tests/provider/helpers/provider-internal-wallets/hd-wallet/fixture.ts
  packages/rpc-proxy/src/index.ts
Labels: Type: Documentation, Type: Enhancement, Type: Feature, Size: Small, Priority: High

#1245 refactor: 1115 `Hash` implementations moved in `vcdm`
  packages/core/src/certificate/certificate.ts
  packages/core/src/core.ts
  packages/core/src/hdkey/HDKey.ts
  packages/core/src/keystore/cryptography/experimental/keystore.ts
  packages/core/src/secp256k1/secp256k1.ts
  packages/core/src/transaction/transaction.ts
  packages/core/src/vcdm/Address.ts
  packages/core/src/vcdm/BloomFilter.ts
  packages/core/src/vcdm/hash/Blake2b256.ts
  packages/core/src/vcdm/hash/Hash.ts
  packages/core/src/vcdm/hash/Keccak256.ts
  packages/core/src/vcdm/hash/Sha256.ts
  packages/core/src/vcdm/hash/index.ts
  packages/core/src/vcdm/index.ts
  packages/core/tests/vcdm/hash/Blake2b256.unit.test.ts
  packages/core/tests/vcdm/hash/Keccak256.unit.test.ts
  packages/core/tests/vcdm/hash/Sha256.unit.test.ts
  packages/core/tests/vcdm/hash/fixture.ts
Labels: Type: Maintenance, Size: Small, Priority: High

#1250 refactor: 1218 FPN unifies integers validation
  docs/diagrams/architecture/vcdm.md
  packages/core/src/encoding/rlp/helpers/numerickind.ts
  packages/core/src/hdkey/HDKey.ts
  packages/core/src/utils/const/data.ts
  packages/core/src/utils/data/data.ts
  packages/core/src/vcdm/FPN.ts
  packages/core/tests/vcdm/FPN.unit.test.ts
Labels: Type: Enhancement, Type: Feature, Size: Small, Priority: High

#1252 1218 remove the dependency on utils for num management
  docs/diagrams/architecture/vcdm.md
  packages/core/src/encoding/rlp/helpers/numerickind.ts
  packages/core/src/hdkey/HDKey.ts
  packages/core/src/utils/data/data.ts
  packages/core/src/vcdm/FPN.ts
  packages/core/tests/utils/data/data.unit.test.ts
  packages/core/tests/utils/data/fixture.ts
  packages/core/tests/utils/revision/fixture.ts
  packages/core/tests/utils/revision/revision.unit.test.ts
  packages/core/tests/vcdm/FPN.unit.test.ts
Labels: Type: Documentation, Type: Feature, Type: Testing, Size: Small, Priority: High

#1258 1122 refactor secp256k1
  apps/sdk-cloudflare-integration/src/index.ts
  docs/accounts.md
  docs/certificates.md
  docs/cryptography.md
  docs/diagrams/architecture/secp256k1.md
  docs/examples/accounts/keystore.ts
  docs/examples/certificates/sign_verify.ts
  docs/examples/cryptography/secp256k1.ts
  docs/examples/transactions/blockref-expiration.ts
  docs/examples/transactions/multiple-clauses.ts
  docs/examples/transactions/sign-decode.ts
  docs/examples/transactions/tx-dependency.ts
  docs/transactions.md
  packages/core/src/certificate/certificate.ts
  packages/core/src/hdkey/HDKey.ts
  packages/core/src/keystore/cryptography/ethers/keystore.ts
  packages/core/src/keystore/cryptography/experimental/keystore.ts
  packages/core/src/secp256k1/Secp256k1.ts
  packages/core/src/secp256k1/index.ts
  packages/core/src/secp256k1/secp256k1.ts
  packages/core/src/transaction/handlers/sign.ts
  packages/core/src/transaction/transaction.ts
  packages/core/src/utils/const/index.ts
  packages/core/src/utils/const/secp256k1.ts
  packages/core/src/vcdm/Address.ts
  packages/core/tests/certificate/fixture.ts
  packages/core/tests/fixture.ts
  packages/core/tests/hdkey/hdkey.unit.test.ts
  packages/core/tests/keystore/keystore.unit.test.ts
  packages/core/tests/secp256k1/secp256k1.unit.test.ts
  packages/core/tests/vcdm/Address.unit.test.ts
  packages/core/tests/vcdm/mnemonic/Mnemonic.unit.test.ts
  packages/core/tests/vcdm/mnemonic/fixture.ts
  packages/hardhat-plugin/src/helpers/provider-helper.ts
  packages/network/src/provider/helpers/provider-internal-wallets/hd-wallet/provider-internal-hd-wallet.ts
  packages/network/src/provider/utils/rpc-mapper/methods-map/methods/eth_getTransactionCount/eth_getTransactionCount.ts
  packages/network/src/signer/signers/vechain-private-key-signer/vechain-private-key-signer.ts
  packages/network/tests/fixture.ts
  packages/network/tests/provider/helpers/provider-internal-wallets/base-wallet/fixture.ts
  packages/network/tests/provider/helpers/provider-internal-wallets/base-wallet/provider-internal-base-wallet.unit.test.ts
  packages/network/tests/provider/rpc-mapper/methods/eth_sendTransaction/eth_sendTransaction.solo.test.ts
  packages/network/tests/signer/signers/vechain-private-key-signer/vechain-private-key-signer.unit.test.ts
  packages/rpc-proxy/src/index.ts
  packages/rpc-proxy/src/utils/validators/validators.ts
Labels: Type: Documentation, Type: Enhancement, Type: Security, Size: Small, Priority: High

#1272 docs: 1113 core diagram reworked
  docs/diagrams/architecture/core-package.md
  packages/core/src/vcdm/account/Account.ts
  packages/core/src/vcdm/currency/Currency.ts
  packages/core/src/vcdm/index.ts
  packages/core/tests/vcdm/account/Account.unit.test.ts
Labels: Type: Documentation, Size: Small, Priority: High

#1287 1113 vet currency
  apps/sdk-nextjs-integration/src/app/transfer-logs/page.tsx
  docs/contracts-erc20.md
  docs/contracts.md
  docs/diagrams/architecture/core-package.md
  docs/diagrams/architecture/vcdm.md
  docs/examples/contracts/contract-create-ERC20-token.ts
  docs/examples/contracts/contract-transfer-ERC20-token.ts
  docs/examples/thor-client/delegated-transactions.ts
  docs/examples/thor-client/transactions.ts
  docs/examples/transactions/blockref-expiration.ts
  docs/examples/transactions/fee-delegation.ts
  docs/examples/transactions/full-flow-delegator-private-key.ts
  docs/examples/transactions/full-flow-delegator-url.ts
  docs/examples/transactions/full-flow-no-delegator.ts
  docs/examples/transactions/multiple-clauses.ts
  docs/examples/transactions/revert-reason-with-simulation.ts
  docs/examples/transactions/sign-decode.ts
  docs/examples/transactions/simulation.ts
  docs/examples/transactions/tx-dependency.ts
  docs/thor-client.md
  docs/transactions.md
  packages/core/package.json
  packages/core/src/utils/index.ts
  packages/core/src/utils/units/index.ts
  packages/core/src/utils/units/types.d.ts
  packages/core/src/utils/units/units.ts
  packages/core/src/vcdm/FPN.ts
  packages/core/src/vcdm/account/Account.ts
  packages/core/src/vcdm/currency/Currency.ts
  packages/core/src/vcdm/currency/Units.ts
  packages/core/src/vcdm/currency/index.ts
  packages/core/src/vcdm/index.ts
  packages/core/tests/clause/clause.unit.test.ts
  packages/core/tests/clause/fixture.ts
  packages/core/tests/utils/units/units.unit.test.ts
  packages/core/tests/vcdm/FPN.unit.test.ts
  packages/core/tests/vcdm/account/Account.unit.test.ts
  packages/core/tests/vcdm/currency/Units.unit.test.ts
  packages/network/solo-seeding/thor-solo-seeding.ts
  packages/network/tests/provider/providers/fixture.ts
  packages/network/tests/provider/rpc-mapper/methods/eth_estimateGas/eth_estimateGas.mock.testnet.test.ts
  packages/network/tests/provider/rpc-mapper/methods/eth_estimateGas/fixture.ts
  packages/network/tests/provider/rpc-mapper/methods/eth_getBalance/fixture.ts
  packages/network/tests/thor-client/accounts/accounts.solo.test.ts
  packages/network/tests/thor-client/contracts/contract.event.mainnet.test.ts
  packages/network/tests/thor-client/gas/fixture.ts
  packages/network/tests/thor-client/transactions/fixture-thorest.ts
  packages/network/tests/thor-client/transactions/fixture.ts
  packages/network/tests/utils/subscriptions/subscriptions.solo.test.ts
  yarn.lock
Labels: Type: Documentation, Type: Enhancement, Type: Feature, Type: Testing, Size: Medium, Priority: High, dependencies

#1294 feat: `ABI` classes
  docs/contracts.md
  docs/diagrams/architecture/vcdm.md
  docs/examples/contracts/contract-create-ERC20-token.ts
  docs/examples/contracts/contract-function-call.ts
  docs/examples/evm-extension/evm-extension.ts
  packages/core/package.json
  packages/core/src/abi/coder.ts
  packages/core/src/abi/fragment.ts
  packages/core/src/abi/helpers/fragment.ts
  packages/core/src/abi/index.ts
  packages/core/src/abi/types.d.ts
  packages/core/src/clause/clause.ts
  packages/core/src/clause/types.d.ts
  packages/core/src/contract/coder.ts
  packages/core/src/core.ts
  packages/core/src/vcdm/Address.ts
  packages/core/src/vcdm/Hex.ts
  packages/core/src/vcdm/abi/ABI.ts
  packages/core/src/vcdm/abi/ABIEthersEvent.ts
  packages/core/src/vcdm/abi/ABIEvent.ts
  packages/core/src/vcdm/abi/ABIFunction.ts
  packages/core/src/vcdm/abi/ABIItem.ts
  packages/core/src/vcdm/abi/index.ts
  packages/core/src/vcdm/index.ts
  packages/core/tests/abi/abi.unit.test.ts
  packages/core/tests/abi/fixture.ts
  packages/core/tests/vcdm/Address.unit.test.ts
  packages/network/src/thor-client/contracts/contracts-module.ts
  packages/network/src/thor-client/contracts/model/contract-factory.ts
  packages/network/src/thor-client/contracts/model/contract-proxy.ts
  packages/network/src/thor-client/contracts/model/contract.ts
  packages/network/src/thor-client/logs/types.d.ts
  packages/network/src/utils/vns/index.ts
  packages/network/tests/provider/providers/hardhat/hardhat-provider.solo.test.ts
  packages/network/tests/provider/providers/vechain/vechain-provider.solo.test.ts
  packages/network/tests/provider/rpc-mapper/methods/eth_signTransaction/eth_signTransaction.testnet.test.ts
  packages/network/tests/signer/signers/vechain-private-key-signer/vechain-private-key-signer.solo.test.ts
  packages/network/tests/signer/signers/vechain-private-key-signer/vechain-private-key-signer.testnet.test.ts
  packages/network/tests/thor-client/contracts/contract.erc20.solo.test.ts
  packages/network/tests/thor-client/contracts/contract.erc721.solo.test.ts
  packages/network/tests/thor-client/contracts/contract.solo.test.ts
  packages/network/tests/thor-client/contracts/fixture.ts
  packages/network/tests/utils/subscriptions/subscriptions.solo.test.ts
Labels: Type: Documentation, Type: Feature, Size: Medium, Priority: High

#1306 feat: 1119 Certificate in dev...
  docs/certificates.md
  docs/diagrams/architecture/certificate.md
  docs/diagrams/architecture/core-package.md
  docs/examples/certificates/sign_verify.ts
  docs/templates/certificates.md
  packages/core/src/certificate/Certificate.ts
  packages/core/src/certificate/CertificateData.ts
  packages/core/src/certificate/certificate.ts
  packages/core/src/certificate/index.ts
  packages/core/src/certificate/types.d.ts
  packages/core/src/vcdm/FPN.ts
  packages/core/src/vcdm/Mnemonic.ts
  packages/core/tests/certificate/Certificate.unit.test.ts
  packages/core/tests/certificate/certificate.unit.test.ts
  packages/core/tests/certificate/fixture.ts
  packages/errors/src/available-errors/certificate/certificate.ts
  packages/errors/tests/available-errors/certificate.unit.test.ts
Labels: Type: Documentation, Type: Enhancement, Type: Feature, Type: Testing, Size: Medium, Priority: High

#1326 1291 class clause
  apps/sdk-cloudflare-integration/src/index.ts
  docs/contracts.md
  docs/diagrams/architecture/core-package.md
  docs/diagrams/architecture/transaction.md
  docs/diagrams/architecture/vcdm.md
  docs/examples/contracts/contract-clauses.ts
  docs/examples/contracts/contract-deploy.ts
  docs/examples/contracts/contract-function-call.ts
  docs/examples/thor-client/delegated-transactions.ts
  docs/examples/thor-client/transactions.ts
  docs/examples/transactions/blockref-expiration.ts
  docs/examples/transactions/fee-delegation.ts
  docs/examples/transactions/full-flow-delegator-private-key.ts
  docs/examples/transactions/full-flow-delegator-url.ts
  docs/examples/transactions/full-flow-no-delegator.ts
  docs/examples/transactions/multiple-clauses.ts
  docs/examples/transactions/sign-decode.ts
  docs/examples/transactions/simulation.ts
  docs/examples/transactions/tx-dependency.ts
  docs/thor-client.md
  docs/transactions.md
  packages/core/src/clause/clause.ts
  packages/core/src/clause/index.ts
  packages/core/src/core.ts
  packages/core/src/transaction/Clause.ts
  packages/core/src/transaction/DeployParams.ts
  packages/core/src/transaction/index.ts
  packages/core/src/transaction/types.d.ts
  packages/core/src/vcdm/FPN.ts
  packages/core/src/vcdm/Hex.ts
  packages/core/src/vcdm/abi/ABIEvent.ts
  packages/core/src/vcdm/currency/Units.ts
  packages/core/src/vcdm/currency/VET.ts
  packages/core/src/vcdm/currency/VTHO.ts
  packages/core/tests/certificate/Certificate.unit.test.ts
  packages/core/tests/clause/Clause.unit.test.ts
  packages/core/tests/clause/clause.unit.test.ts
  packages/core/tests/clause/fixture.ts
  packages/core/tests/hdkey/HDKey.unit.test.ts
  packages/core/tests/secp256k1/Secp256k1.unit.test.ts
  packages/core/tests/vcdm/FPN.unit.test.ts
  packages/core/tests/vcdm/currency/Units.unit.test.ts
  packages/core/tests/vcdm/mnemonic/Mnemonic.unit.test.ts
  packages/network/solo-seeding/thor-solo-seeding.ts
  packages/network/src/signer/signers/vechain-abstract-signer/vechain-abstract-signer.ts
  packages/network/src/thor-client/contracts/contracts-module.ts
  packages/network/src/thor-client/contracts/model/contract-factory.ts
  packages/network/src/thor-client/contracts/model/contract-proxy.ts
  packages/network/src/thor-client/contracts/types.d.ts
  packages/network/tests/provider/providers/vechain/vechain-provider.solo.test.ts
  packages/network/tests/provider/rpc-mapper/methods/eth_estimateGas/eth_estimateGas.mock.testnet.test.ts
  packages/network/tests/provider/rpc-mapper/methods/eth_estimateGas/fixture.ts
  packages/network/tests/signer/signers/vechain-private-key-signer/vechain-private-key-signer.solo.test.ts
  packages/network/tests/signer/signers/vechain-private-key-signer/vechain-private-key-signer.testnet.test.ts
  packages/network/tests/utils/subscriptions/subscriptions.solo.test.ts
Labels: Type: Documentation, Type: Enhancement, Type: Feature, Type: Testing, Size: Medium, Priority: High

#1338 feat: 1291 Clause class in action
  apps/sdk-nextjs-integration/src/app/transfer-logs/page.tsx
  docs/diagrams/architecture/core-package.md
  docs/diagrams/architecture/transaction.md
  docs/diagrams/architecture/vcdm.md
  packages/core/src/encoding/rlp/helpers/numerickind.ts
  packages/core/src/hdkey/HDKey.ts
  packages/core/src/transaction/Clause.ts
  packages/core/src/vcdm/FixedPointNumber.ts
  packages/core/src/vcdm/currency/Coin.ts
  packages/core/src/vcdm/currency/Currency.ts
  packages/core/src/vcdm/currency/Units.ts
  packages/core/src/vcdm/currency/VET.ts
  packages/core/src/vcdm/currency/VTHO.ts
  packages/core/src/vcdm/index.ts
  packages/core/tests/vcdm/FixedPointNumber.unit.test.ts
  packages/core/tests/vcdm/account/Account.unit.test.ts
  packages/core/tests/vcdm/currency/Coin.unit.test.ts
  packages/core/tests/vcdm/currency/Units.unit.test.ts
  packages/core/tests/vcdm/currency/VET.unit.test.ts
  packages/core/tests/vcdm/currency/VTHO.unit.test.ts
  packages/network/tests/thor-client/accounts/accounts.solo.test.ts
  packages/network/tests/thor-client/contracts/contract.event.mainnet.test.ts
Labels: Type: Documentation, Size: Small, Priority: High

#1364 998 (no-breaking changes) get account utility functions
  packages/network/src/thor-client/accounts/accounts-module.ts
  packages/network/src/thor-client/accounts/types.d.ts
  packages/network/tests/thor-client/accounts/accounts.solo.test.ts
Labels: Type: Enhancement, Type: Feature, Size: Small, Priority: Low
