Repository vechain/vechain-sdk-js, pull requests merged in 2024-05, with the labels that each got.

#854 docs: 841 SDK core import with NextJS
  README.md
Labels: Type: Bug, Type: Documentation

#853 666 pure and secure keystore
  docs/accounts.md
  docs/examples/accounts/keystore.ts
  package.json
  packages/core/src/keystore/keystore.ts
  packages/core/src/keystore/types.d.ts
  packages/core/src/utils/const/index.ts
  packages/core/src/utils/const/keystore.ts
  packages/core/tests/keystore/keystore.unit.test.ts
  yarn.lock
Labels: Type: Enhancement, Type: Security

#863 809 thordevkit compatible certificate validation
  packages/core/src/certificate/certificate.ts
  packages/core/tests/certificate/certificate.unit.test.ts
  packages/core/tests/certificate/fixture.ts
Labels: Type: Bug, Type: Documentation, Type: Enhancement

#886 refactor: 666 pure and secure `packages/core/src/clause.ts`
  packages/core/src/address/address.ts
  packages/core/src/clause/clause.ts
Labels: Type: Enhancement, Size: Small

#884 feat: experimental cryptography for keystore
  README.md
  docs/accounts.md
  docs/examples/accounts/keystore.ts
  packages/core/package.json
  packages/core/src/keystore/cryptography/ethers/const/index.ts
  packages/core/src/keystore/cryptography/ethers/const/keystore.ts
  packages/core/src/keystore/cryptography/ethers/index.ts
  packages/core/src/keystore/cryptography/ethers/keystore.ts
  packages/core/src/keystore/cryptography/experimental/index.ts
  packages/core/src/keystore/cryptography/experimental/keystore.ts
  packages/core/src/keystore/cryptography/index.ts
  packages/core/src/keystore/keystore.ts
  packages/core/src/keystore/types.d.ts
  packages/core/tests/keystore/keystore.unit.test.ts
  yarn.lock
Labels: Type: Feature, Priority: High

#874 refactor: 666 pure and secure units.ts
  packages/core/package.json
  packages/core/src/utils/units/types.d.ts
  packages/core/src/utils/units/units.ts
  packages/core/tests/utils/units/fixture.ts
  packages/core/tests/utils/units/units.unit.test.ts
  yarn.lock
Labels: Type: Enhancement, javascript

#909 fix: 897 test race condition
  packages/network/tests/provider/rpc-mapper/methods/eth_sendTransaction/eth_sendTransaction.solo.test.ts
Labels: Type: Bug, Size: Small, Priority: Medium

#917 feat: 802 composable bloom filters
  packages/core/src/bloom/bloom.ts
  packages/core/tests/bloom/bloom.unit.test.ts
  yarn.lock
Labels: Type: Enhancement, Type: Feature, Size: Small, Priority: Medium
