Repository vechain/vechain-sdk-js, pull requests merged in 2024-12, with the labels that each got.

#1559 feat: add example for interacting with contract
  docs/examples/contracts/contract-usage.ts
Labels: Type: Documentation

#1561 fix: 1560 Transaction.ts allows making of incomplete signed instances
  packages/core/src/transaction/Transaction.ts
  packages/core/tests/transaction/Transaction.unit.test.ts
Labels: Type: Bug, Type: Enhancement, Size: Small, Priority: High

#1596 1595 refactor the transaction class using only the concept of sender and gas payer
  docs/diagrams/architecture/transaction.md
  docs/examples/thor-client/delegated-transactions.ts
  docs/examples/transactions/fee-delegation.ts
  docs/examples/transactions/full-flow-delegator-private-key.ts
  docs/thor-client.md
  docs/transactions.md
  packages/core/src/transaction/Transaction.ts
  packages/core/tests/transaction/Transaction.unit.test.ts
  packages/network/src/signer/signers/vechain-private-key-signer/vechain-private-key-signer.ts
  packages/network/tests/thor-client/transactions/transactions-thorest.solo.test.ts
Labels: Priority: Low
